import argparse


parser = argparse.ArgumentParser(prog='Калитка Престиж',
                                 description='Генерирует чертижи для калиток Аполло')
parser.add_argument('--debug', action='store_true', help='Режим отладки')
parser.add_argument('--order', help='Номер заказа')
parser.add_argument('--customer', help='Заказчик')
parser.add_argument('--date', help='Дата готовности')
parser.add_argument('--engineer', help='Инженер')
parser.add_argument('--width', help='Ширина калитки')
parser.add_argument('--height', help='Высота калитки')
parser.add_argument('--open', help='Направление открытия')
parser.add_argument('--side', help='Сторона петель')
parser.add_argument('--frame_type', help='Тип коробки')
parser.add_argument('--cliarance', help='Просвет под створкой')
parser.add_argument('--bridge', help='Тип перемычки')
parser.add_argument('--bridge_height', help='Высота фрамуги')
parser.add_argument('--fill', help='Тип заполнения')
parser.add_argument('--frame_color', help='Цвет рамы')
parser.add_argument('--color_type', help='Структура покраски рамы')
parser.add_argument('--fill_color_in', help='Цвет заполнения изнутри')
parser.add_argument('--fill_color_out', help='Цвет заполнения снаружи')
parser.add_argument('--lock', help='Замок')
parser.add_argument('--auto_closer', help='Доводчик')
parser.add_argument('--handle_in', help='Вид ручки изнутри')
parser.add_argument('--handle_out', help='Вид ручки снаружи')
parser.add_argument('--batten', help='Нащельник')
parser.add_argument('--batten_num', help='Кол-во нащельников')
parser.add_argument('--comments', help='Комментарий')
